version: "3.9"

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend-issue
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml  
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.monitoring.enabled: "true"
    volumes:
      - dados-elasticsearch:/usr/share/elasticsearch/data  

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    networks:
      - backend-issue
    configs:
      - source: logstash_config
        target: /etc/logstash/conf.d  
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    networks:
      - backend-issue
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml  
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0
      MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: true
    depends_on:
      - elasticsearch 

networks:
  backend-issue:
    driver: bridge

volumes:
  pg-data-issue:
  dados-rabbitmq-issue:
  dados-elasticsearch:
  
configs:
  elastic_config:
    file: ./../elk/elasticsearch/config/elasticsearch.yml
  kibana_config:
    file: ./../elk/kibana/config/kibana.yml
  logstash_config:
    file: ./../elk/logstash